<br>

<div class="row">
	<div class="col-md-12 text-center">
		<span><i class="fa fa-user fa-2x"></i></span>
		<h2>Login</h2>
		<br>
				<?php
    $form = $this->form;
    $form->setAttribute ( 'action', $this->url ( 'login/process', array (
      'action' => 'authenticate' 
    ) ) );
    $form->prepare ();
    
    echo $this->form ()->openTag ( $form );
    echo $this->formRow ( $form->get ( 'username' ) );
    echo "<br/>";
    echo $this->formRow ( $form->get ( 'password' ) );
    echo "<br/>";
    echo "<br/>";
    //echo $this->formRow ( $form->get ( 'submit' ) );
    echo "<button type=\"submit\" class=\"btn btn-info\"><span><i class=\"fa fa-sign-in fa-lg\"></i></span> Login</button>";
    echo $this->form ()->closeTag ();
    
    if ($this->messages) {
     echo '<ul>';
     foreach ( $this->messages as $message ) {
      echo '<li>' . $message . '</li>';
     }
     echo '</ul>';
    }
    ?>
			</div>
</div>
