<h1>Add</h1>
<?php
$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

       
<?php
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
$form->get('title')->setAttribute('placeholder','Title of the album...');
$form->get('artist')->setAttribute('placeholder','Artist of the album...');
echo $this->formRow($form->get('title')) . "<br>";
echo $this->formRow($form->get('artist')) . "<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
