<!-- === BEGIN HEADER === -->
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
<!-- Title -->
<title>Substance - Professional Bootstrap Template</title>
<!-- Meta -->
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport"
	content="width=device-width, initial-scale=1, maximum-scale=1" />
<!-- Favicon -->
<link href="favicon.html" rel="shortcut icon">
<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href="css/bootstrap.css" rel="stylesheet">
<!-- Template CSS -->
<link rel="stylesheet" href="css/animate.css" rel="stylesheet">
<link rel="stylesheet" href="css/font-awesome.css" rel="stylesheet">
<link rel="stylesheet" href="css/nexus.css" rel="stylesheet">
<link rel="stylesheet" href="css/responsive.css" rel="stylesheet">
<link rel="stylesheet" href="css/custom.css" rel="stylesheet">
<!-- Google Fonts-->
<link href="http://fonts.googleapis.com/css?family=Lato:400,300"
	rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300"
	rel="stylesheet" type="text/css">
</head>
<body>
	<div id="header" class="container">
		<div class="row" style="text-align: center;">
			<!-- Logo -->
			<img alt="Dai-hoc-fpt" src="img/fpt.png" height="110.8" width="500">
			<!-- End Logo -->
			<!-- Top Menu -->

			<div class="clear"></div>
			<!-- End Top Menu -->
		</div>
	</div>
	<!-- === END HEADER === -->
	<!-- === BEGIN CONTENT === -->

	<div id="content" class="container">
		<div class="row margin-top-30">
			<div class="col-md-12 text-center">
				<h2 class="text-center">Welcome to FPT University iBoard</h2>
				<p class="text-center">This page is for admin to manage departments,
					instructors, students and subjects in school.</p>
			</div>
		</div>
		<?php 
		   $user = $this->identity();
           if (empty($user)) { ?>
            <div class="row margin-top-30">
			<div class="col-md-12 text-center">
				<a class="btn btn-warning btn-lg active" href="auth"><span><i class="fa fa-sign-in fa-lg"></i></span> Please login to continue!</a>
			</div>
		</div>
           <?php } else { ?>
	
		<div class="row">
			<div class="portfolio-group col-md-12 no-padding">
				<div class="row">
					<!-- Portfolio -->
					<!-- Portfolio Item -->
					<div class="portfolio-item col-md-3 animate fadeIn">
						<div class="image-hover" style="height: 370px">
							<a href="#">
								<figure>
									<img src="img/frontpage/institution.png" alt="image1" style="height: 200px">
									<div class="overlay">
										<a class="expand" href="department">Image Link</a>
									</div>
								</figure>
								<h3 class="margin-top-20">Manage departments</h3>
								<p class="margin-top-10 margin-bottom-20">View and edit
									departments in FU.</p>
							</a>
						</div>
					</div>
					<!-- //Portfolio Item// -->

					<!-- Portfolio Item -->
					<div class="portfolio-item col-md-3 animate fadeIn">
						<div class="image-hover" style="height: 370px">
							<a href="#">
								<figure>
									<img src="img/frontpage/student.png" alt="image2" style="height: 200px">
									<div class="overlay">
										<a class="expand" href="student">Image Link</a>
									</div>
								</figure>
								<h3 class="margin-top-20">Manage students</h3>
								<p class="margin-top-10 margin-bottom-20">View and edit students
									in FU.</p>
							</a>
						</div>
					</div>
					<!-- //Portfolio Item// -->
					
					<!-- Portfolio Item -->
					<div class="portfolio-item col-md-3 animate fadeIn">
						<div class="image-hover" style="height: 370px">
							<a href="#">
								<figure>
									<img src="img/frontpage/teacher.png" alt="image2" style="height: 200px">
									<div class="overlay">
										<a class="expand" href="department">Image Link</a>
									</div>
								</figure>
								<h3 class="margin-top-20">Manage instructors</h3>
								<p class="margin-top-10 margin-bottom-20">View and edit instructors
									in FU.</p>
							</a>
						</div>
					</div>
					<!-- //Portfolio Item// -->
					
					<!-- Portfolio Item -->
					<div class="portfolio-item col-md-3 animate fadeIn">
						<div class="image-hover" style="height: 370px">
							<a href="#">
								<figure>
									<img src="img/frontpage/subject.png" alt="image2" style="height: 200px">
									<div class="overlay">
										<a class="expand" href="department">Image Link</a>
									</div>
								</figure>
								<h3 class="margin-top-20">Manage subjects</h3>
								<p class="margin-top-10 margin-bottom-20">View and edit subjects
									in FU.</p>
							</a>
						</div>
					</div>
					<!-- //Portfolio Item// -->
					
					<!-- End Portfolio -->
				</div>
			</div>
		</div> <?php }?>
		<!-- === END CONTENT === -->
		<!-- === BEGIN FOOTER === -->
		<div id="base">


			<!-- Footer Menu -->

		</div>
		<!-- End Footer Menu -->
	</div>

	<!-- JS -->
	<script type="text/javascript" src="js/jquery.min.js"
		type="text/javascript"></script>
	<script type="text/javascript" src="js/bootstrap.min.js"
		type="text/javascript"></script>
	<script type="text/javascript" src="js/scripts.js"></script>
	<!-- Isotope - Portfolio Sorting -->
	<script type="text/javascript" src="js/jquery.isotope.js"
		type="text/javascript"></script>
	<!-- Mobile Menu - Slicknav -->
	<script type="text/javascript" src="js/jquery.slicknav.js"
		type="text/javascript"></script>
	<!-- Animate on Scroll-->
	<script type="text/javascript" src="js/jquery.visible.js"
		charset="utf-8"></script>
	<!-- Slimbox2-->
	<script type="text/javascript" src="js/slimbox2.js" charset="utf-8"></script>
	<!-- Modernizr -->
	<script src="js/modernizr.custom.js" type="text/javascript"></script>
	<!-- End JS -->
</body>
</html>
<!-- === END FOOTER === -->