<h1>Add</h1>
<?php
$title = 'Add new department';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

       
<?php
$form->setAttribute('action', $this->url('department', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
// $form->get('deptCode')->setAttribute('placeholder','Code of the department...');
// $form->get('deptName')->setAttribute('placeholder','Name of the department...');
// $form->get('deptOffice')->setAttribute('placeholder','Office of the department...');
// $form->get('deptPhone')->setAttribute('placeholder','Phone of the department...');
echo $this->formRow($form->get('deptCode')) . "<br>";
echo $this->formRow($form->get('deptName')) . "<br>";
echo $this->formRow($form->get('deptOffice')) . "<br>";
echo $this->formRow($form->get('deptPhone')) . "<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
