<h1>Delete</h1>
<?php
$title = 'Delete department';
$this->headTitle ( $title );
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure that you want to delete department
'<?php echo $this->escapeHtml($department->deptName); ?>'?
</p>
<?php

$url = $this->url ( 'department', array (
  'action' => 'delete',
  'id' => $this->id, 
) );
?>
<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="submit" name="del" value="Yes" class="btn btn-warning"/> <input type="submit"
			name="del" value="No" class="btn btn-info" />
	</div>
</form>