<h1>Edit</h1>
<?php
$title = 'Edit department';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
'department',
array(
'action' => 'edit',
'deptCode' => $this->deptCode,
)
));
$form->prepare();
echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('deptCode')) . "<br>";
echo $this->formRow($form->get('deptName')) . "<br>";
echo $this->formRow($form->get('deptOffice')) . "<br>";
echo $this->formRow($form->get('deptPhone')) . "<br>";
//echo $this->formSubmit($form->get('submit'));
echo "<button type=\"submit\" class=\"btn btn-success\"><span><i class=\"fa fa-save\"></i></span> Save</button>";
echo $this->form()->closeTag();