<h1>Delete</h1>
<?php
$title = 'Delete student';
$this->headTitle ( $title );
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure that you want to delete student
'<?php echo $this->escapeHtml($student->stuName); ?>'?
</p>
<?php

$url = $this->url ( 'student', array (
  'action' => 'delete',
  'id' => $this->id, 
) );
?>
<form action="<?php echo $url; ?>" method="post">
	<div>
		<button type="submit" class="btn btn-warning" value="Yes" name="del"><span><i class="fa fa-check"></i></span> Yes</button>
		<button type="submit" class="btn btn-info" value="No" name="del"><span><i class="fa fa-times"></i></span> No</button>
	</div>
</form>