<h1>Index</h1>
<?php
$title = 'My students';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('student', array('action'=>'add'));?>" class="btn btn-primary">
	<span><i class="fa fa-plus-circle"></i></span> Add new student</a>
</p>
<table class="table">
	<tr>
		<th>Code</th>
		<th>SSN</th>
		<th>Name</th>
		<th>Birthdate</th>
		<th>Sex</th>
		<th>Address</th>
		<th>&nbsp;</th>
	</tr>
<?php foreach ($students as $student) : ?>
<tr>
		<td><?php echo $this->escapeHtml($student->stuCode);?></td>
		<td><?php echo $this->escapeHtml($student->stuSSN);?></td>
		<td><?php echo $this->escapeHtml($student->stuName);?></td>
		<td><?php echo $this->escapeHtml($student->stuBirthdate);?></td>
		<td><?php echo $this->escapeHtml($student->stuSex);?></td>
		<td><?php echo $this->escapeHtml($student->stuAddress);?></td>
		<td><a
			href="<?php
    
echo $this->url('student', array(
        'action' => 'edit',
        'id' => $student->stuCode
    ));
    ?>" class="btn btn-info"><span><i class="fa fa-edit"></i></span> Edit</a> <a
			href="<?php
    
echo $this->url('student', array(
        'action' => 'delete',
        'id' => $student->stuCode
    ));
    ?>" class="btn btn-danger"><span><i class="fa fa-minus-circle"></i></span> Delete</a></td>
	</tr>
<?php endforeach; ?>
</table>

